### ISSUE TITLE
Exposure in low light photo ends up too dark.

### ISSUE THREAD

**Issue by cityeyes** [RandoApp/Rando-android#197]
First off, I'm using a Nexus 5 with stock ROM.

Now, onto the problem:
When I focus and compose my photos, the exposure adjusts properly, but when I actually capture the photo, while the focus remains correct, the exposure in low-light photos often reverts to a point where it's far too low to send to a potential rando recipient.

Example here -
While focusing: http://i.imgur.com/K2Xy8eD.png
Captured image: http://i.imgur.com/lsVbacW.png

Let me know if you'd like to know anything else.

**Comment by xp-vit** [comment]
Done as a part of https://github.com/RandoApp/Rando-android/pull/277
