### ISSUE TITLE
RuntimeException: startPreview failed

### ISSUE THREAD

**Issue by dimhold** [RandoApp/Rando-android#209]
|phone|GT-I9300|
|--------------|:--------:|
|version|1.0.12|
|code version|34|
|android|4.3|
|Error|RuntimeException at com.commonsware.cwac.camera.CameraView.startPreview(CameraView.java:532)|

Stacktrace:
 java.lang.RuntimeException: startPreview failed at android.hardware.Camera.startPreview(Native Method) at com.commonsware.cwac.camera.CameraView.startPreview(CameraView.java:532) at com.commonsware.cwac.camera.CameraView.initPreview(CameraView.java:527) at com.commonsware.cwac.camera.CameraView.initPreview(CameraView.java:510) at com.commonsware.cwac.camera.TexturePreviewStrategy.onSurfaceTextureAvailable(TexturePreviewStrategy.java:45) at android.view.TextureView.getHardwareLayer(TextureView.java:385) at android.view.View.getDisplayList(View.java:13709) at android.view.View.getDisplayList(View.java:13786) at android.view.View.draw(View.java:14563) at android.view.ViewGroup.drawChild(ViewGroup.java:3316) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153) at android.view.View.getDisplayList(View.java:13739) at android.view.View.getDisplayList(View.java:13786) at android.view.View.draw(View.java:14563) at android.view.ViewGroup.drawChild(ViewGroup.java:3316) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153) at android.view.View.getDisplayList(View.java:13739) at android.view.View.getDisplayList(View.java:13786) at android.view.View.draw(View.java:14563) at android.view.ViewGroup.drawChild(ViewGroup.java:3316) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153) at android.view.View.getDisplayList(View.java:13739) at android.view.View.getDisplayList(View.java:13786) at android.view.View.draw(View.java:14563) at android.view.ViewGroup.drawChild(ViewGroup.java:3316) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153) at android.view.View.getDisplayList(View.java:13739) at android.view.View.getDisplayList(View.java:13786) at android.view.View.draw(View.java:14563) at android.view.ViewGroup.drawChild(ViewGroup.java:3316) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153) at android.view.View.getDisplayList(View.java:13739) at android.view.View.getDisplayList(View.java:13786) at android.view.View.draw(View.java:14563) at android.view.ViewGroup.drawChild(ViewGroup.java:3316) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153) at android.view.View.getDisplayList(View.java:13739) at android.view.View.getDisplayList(View.java:13786) at android.view.View.draw(View.java:14563) at android.view.ViewGroup.drawChild(ViewGroup.java:3316) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153) at android.view.View.draw(View.java:14856) at android.widget.FrameLayout.draw(FrameLayout.java:467) at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2621) at android.view.View.getDisplayList(View.java:13744) at android.view.View.getDisplayList(View.java:13786) at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1411) at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1359) at android.view.ViewRootImpl.draw(ViewRootImpl.java:2672) at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2538) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2154) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791) at android.view.Choreographer.doCallbacks(Choreographer.java:591) at android.view.Choreographer.doFrame(Choreographer.java:561) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777) at android.os.Handler.handleCallback(Handler.java:730) at android.os.Handler.dispatchMessage(Handler.java:92) at android.os.Looper.loop(Looper.java:176) at android.app.ActivityThread.main(ActivityThread.java:5419) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:525) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862) at dalvik.system.NativeStart.main(Native Method)

**Comment by xp-vit** [comment]
It will be reopen if still exist in new version.
