### ISSUE TITLE
Upload animation is frozen after scrolling

### ISSUE THREAD

**Issue by dimhold** [RandoApp/Rando-android#325]
Steps to reproduce:
1. Disable any Network connection
2. Make a rando
3. Verifty that you can see upload animation
4. Scroll down
5. Scroll up

Actual: After scrolling upload animation is frozen
Expected: After scrolling upload animation should work

https://youtu.be/ju4-abZu3oQ

**Comment by xp-vit** [comment]
Seems to be fixed in 1.2.4
